# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(837, 551)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.canvas = QtWidgets.QLabel(self.centralWidget)
        self.canvas.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)
        self.canvas.setText("")
        self.canvas.setObjectName("canvas")
        self.verticalLayout_2.addWidget(self.canvas)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.centralWidget)
        self.widget_3.setMinimumSize(QtCore.QSize(78, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(78, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.secondaryButton = QtWidgets.QPushButton(self.widget_3)
        self.secondaryButton.setGeometry(QtCore.QRect(30, 10, 40, 40))
        self.secondaryButton.setMinimumSize(QtCore.QSize(40, 40))
        self.secondaryButton.setMaximumSize(QtCore.QSize(40, 40))
        self.secondaryButton.setText("")
        self.secondaryButton.setObjectName("secondaryButton")
        self.primaryButton = QtWidgets.QPushButton(self.widget_3)
        self.primaryButton.setGeometry(QtCore.QRect(10, 0, 40, 40))
        self.primaryButton.setMinimumSize(QtCore.QSize(40, 40))
        self.primaryButton.setMaximumSize(QtCore.QSize(40, 40))
        self.primaryButton.setText("")
        self.primaryButton.setObjectName("primaryButton")
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.centralWidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(15, 0, 15, 15)
        self.gridLayout_2.setSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.roundrectButton = QtWidgets.QPushButton(self.widget_2)
        self.roundrectButton.setMinimumSize(QtCore.QSize(30, 30))
        self.roundrectButton.setMaximumSize(QtCore.QSize(30, 30))
        self.roundrectButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/layer-shape-round.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.roundrectButton.setIcon(icon)
        self.roundrectButton.setCheckable(True)
        self.roundrectButton.setObjectName("roundrectButton")
        self.gridLayout_2.addWidget(self.roundrectButton, 1, 12, 1, 1)
        self.sprayButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sprayButton.sizePolicy().hasHeightForWidth())
        self.sprayButton.setSizePolicy(sizePolicy)
        self.sprayButton.setMinimumSize(QtCore.QSize(30, 30))
        self.sprayButton.setMaximumSize(QtCore.QSize(30, 30))
        self.sprayButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/spray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sprayButton.setIcon(icon1)
        self.sprayButton.setCheckable(True)
        self.sprayButton.setFlat(False)
        self.sprayButton.setObjectName("sprayButton")
        self.gridLayout_2.addWidget(self.sprayButton, 0, 8, 1, 1)
        self.stampButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stampButton.sizePolicy().hasHeightForWidth())
        self.stampButton.setSizePolicy(sizePolicy)
        self.stampButton.setMinimumSize(QtCore.QSize(30, 30))
        self.stampButton.setMaximumSize(QtCore.QSize(30, 30))
        self.stampButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/cake.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stampButton.setIcon(icon2)
        self.stampButton.setCheckable(True)
        self.stampButton.setObjectName("stampButton")
        self.gridLayout_2.addWidget(self.stampButton, 0, 9, 1, 1)
        self.colorButton_7 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_7.sizePolicy().hasHeightForWidth())
        self.colorButton_7.setSizePolicy(sizePolicy)
        self.colorButton_7.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_7.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_7.setText("")
        self.colorButton_7.setObjectName("colorButton_7")
        self.gridLayout_2.addWidget(self.colorButton_7, 1, 0, 1, 1)
        self.fillButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fillButton.sizePolicy().hasHeightForWidth())
        self.fillButton.setSizePolicy(sizePolicy)
        self.fillButton.setMinimumSize(QtCore.QSize(30, 30))
        self.fillButton.setMaximumSize(QtCore.QSize(30, 30))
        self.fillButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/paint-can.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fillButton.setIcon(icon3)
        self.fillButton.setCheckable(True)
        self.fillButton.setObjectName("fillButton")
        self.gridLayout_2.addWidget(self.fillButton, 1, 9, 1, 1)
        self.selectrectButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectrectButton.sizePolicy().hasHeightForWidth())
        self.selectrectButton.setSizePolicy(sizePolicy)
        self.selectrectButton.setMinimumSize(QtCore.QSize(30, 30))
        self.selectrectButton.setMaximumSize(QtCore.QSize(30, 30))
        self.selectrectButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/selection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectrectButton.setIcon(icon4)
        self.selectrectButton.setCheckable(True)
        self.selectrectButton.setObjectName("selectrectButton")
        self.gridLayout_2.addWidget(self.selectrectButton, 0, 15, 1, 1)
        self.colorButton_9 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_9.sizePolicy().hasHeightForWidth())
        self.colorButton_9.setSizePolicy(sizePolicy)
        self.colorButton_9.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_9.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_9.setText("")
        self.colorButton_9.setObjectName("colorButton_9")
        self.gridLayout_2.addWidget(self.colorButton_9, 1, 2, 1, 1)
        self.colorButton_2 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_2.sizePolicy().hasHeightForWidth())
        self.colorButton_2.setSizePolicy(sizePolicy)
        self.colorButton_2.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_2.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_2.setText("")
        self.colorButton_2.setObjectName("colorButton_2")
        self.gridLayout_2.addWidget(self.colorButton_2, 0, 1, 1, 1)
        self.colorButton_6 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_6.sizePolicy().hasHeightForWidth())
        self.colorButton_6.setSizePolicy(sizePolicy)
        self.colorButton_6.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_6.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_6.setText("")
        self.colorButton_6.setObjectName("colorButton_6")
        self.gridLayout_2.addWidget(self.colorButton_6, 0, 5, 1, 1)
        self.textButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textButton.sizePolicy().hasHeightForWidth())
        self.textButton.setSizePolicy(sizePolicy)
        self.textButton.setMinimumSize(QtCore.QSize(30, 30))
        self.textButton.setMaximumSize(QtCore.QSize(30, 30))
        self.textButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.textButton.setIcon(icon5)
        self.textButton.setCheckable(True)
        self.textButton.setObjectName("textButton")
        self.gridLayout_2.addWidget(self.textButton, 1, 17, 1, 1)
        self.selectpolyButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectpolyButton.sizePolicy().hasHeightForWidth())
        self.selectpolyButton.setSizePolicy(sizePolicy)
        self.selectpolyButton.setMinimumSize(QtCore.QSize(30, 30))
        self.selectpolyButton.setMaximumSize(QtCore.QSize(30, 30))
        self.selectpolyButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/selection-poly.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectpolyButton.setIcon(icon6)
        self.selectpolyButton.setCheckable(True)
        self.selectpolyButton.setObjectName("selectpolyButton")
        self.gridLayout_2.addWidget(self.selectpolyButton, 0, 17, 1, 1)
        self.ellipseButton = QtWidgets.QPushButton(self.widget_2)
        self.ellipseButton.setMinimumSize(QtCore.QSize(30, 30))
        self.ellipseButton.setMaximumSize(QtCore.QSize(30, 30))
        self.ellipseButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/layer-shape-ellipse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ellipseButton.setIcon(icon7)
        self.ellipseButton.setCheckable(True)
        self.ellipseButton.setObjectName("ellipseButton")
        self.gridLayout_2.addWidget(self.ellipseButton, 0, 13, 1, 1)
        self.colorButton_12 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_12.sizePolicy().hasHeightForWidth())
        self.colorButton_12.setSizePolicy(sizePolicy)
        self.colorButton_12.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_12.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_12.setText("")
        self.colorButton_12.setObjectName("colorButton_12")
        self.gridLayout_2.addWidget(self.colorButton_12, 1, 5, 1, 1)
        self.eraserButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eraserButton.sizePolicy().hasHeightForWidth())
        self.eraserButton.setSizePolicy(sizePolicy)
        self.eraserButton.setMinimumSize(QtCore.QSize(30, 30))
        self.eraserButton.setMaximumSize(QtCore.QSize(30, 30))
        self.eraserButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eraserButton.setIcon(icon8)
        self.eraserButton.setCheckable(True)
        self.eraserButton.setObjectName("eraserButton")
        self.gridLayout_2.addWidget(self.eraserButton, 1, 15, 1, 1)
        self.penButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.penButton.sizePolicy().hasHeightForWidth())
        self.penButton.setSizePolicy(sizePolicy)
        self.penButton.setMinimumSize(QtCore.QSize(30, 30))
        self.penButton.setMaximumSize(QtCore.QSize(30, 30))
        self.penButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.penButton.setIcon(icon9)
        self.penButton.setCheckable(True)
        self.penButton.setObjectName("penButton")
        self.gridLayout_2.addWidget(self.penButton, 0, 7, 1, 1)
        self.colorButton_8 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_8.sizePolicy().hasHeightForWidth())
        self.colorButton_8.setSizePolicy(sizePolicy)
        self.colorButton_8.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_8.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_8.setText("")
        self.colorButton_8.setObjectName("colorButton_8")
        self.gridLayout_2.addWidget(self.colorButton_8, 1, 1, 1, 1)
        self.polygonButton = QtWidgets.QPushButton(self.widget_2)
        self.polygonButton.setMinimumSize(QtCore.QSize(30, 30))
        self.polygonButton.setMaximumSize(QtCore.QSize(30, 30))
        self.polygonButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/layer-shape-polygon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.polygonButton.setIcon(icon10)
        self.polygonButton.setCheckable(True)
        self.polygonButton.setObjectName("polygonButton")
        self.gridLayout_2.addWidget(self.polygonButton, 1, 13, 1, 1)
        self.polylineButton = QtWidgets.QPushButton(self.widget_2)
        self.polylineButton.setMinimumSize(QtCore.QSize(30, 30))
        self.polylineButton.setMaximumSize(QtCore.QSize(30, 30))
        self.polylineButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("images/layer-shape-polyline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.polylineButton.setIcon(icon11)
        self.polylineButton.setCheckable(True)
        self.polylineButton.setObjectName("polylineButton")
        self.gridLayout_2.addWidget(self.polylineButton, 1, 11, 1, 1)
        self.dropperButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dropperButton.sizePolicy().hasHeightForWidth())
        self.dropperButton.setSizePolicy(sizePolicy)
        self.dropperButton.setMinimumSize(QtCore.QSize(30, 30))
        self.dropperButton.setMaximumSize(QtCore.QSize(30, 30))
        self.dropperButton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("images/pipette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dropperButton.setIcon(icon12)
        self.dropperButton.setCheckable(True)
        self.dropperButton.setObjectName("dropperButton")
        self.gridLayout_2.addWidget(self.dropperButton, 1, 8, 1, 1)
        self.lineButton = QtWidgets.QPushButton(self.widget_2)
        self.lineButton.setMinimumSize(QtCore.QSize(30, 30))
        self.lineButton.setMaximumSize(QtCore.QSize(30, 30))
        self.lineButton.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("images/layer-shape-line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lineButton.setIcon(icon13)
        self.lineButton.setCheckable(True)
        self.lineButton.setObjectName("lineButton")
        self.gridLayout_2.addWidget(self.lineButton, 0, 11, 1, 1)
        self.colorButton_10 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_10.sizePolicy().hasHeightForWidth())
        self.colorButton_10.setSizePolicy(sizePolicy)
        self.colorButton_10.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_10.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_10.setText("")
        self.colorButton_10.setObjectName("colorButton_10")
        self.gridLayout_2.addWidget(self.colorButton_10, 1, 3, 1, 1)
        self.colorButton_1 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_1.sizePolicy().hasHeightForWidth())
        self.colorButton_1.setSizePolicy(sizePolicy)
        self.colorButton_1.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_1.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_1.setStyleSheet("")
        self.colorButton_1.setText("")
        self.colorButton_1.setObjectName("colorButton_1")
        self.gridLayout_2.addWidget(self.colorButton_1, 0, 0, 1, 1)
        self.colorButton_3 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_3.sizePolicy().hasHeightForWidth())
        self.colorButton_3.setSizePolicy(sizePolicy)
        self.colorButton_3.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_3.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_3.setText("")
        self.colorButton_3.setObjectName("colorButton_3")
        self.gridLayout_2.addWidget(self.colorButton_3, 0, 2, 1, 1)
        self.colorButton_11 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_11.sizePolicy().hasHeightForWidth())
        self.colorButton_11.setSizePolicy(sizePolicy)
        self.colorButton_11.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_11.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_11.setText("")
        self.colorButton_11.setObjectName("colorButton_11")
        self.gridLayout_2.addWidget(self.colorButton_11, 1, 4, 1, 1)
        self.brushButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brushButton.sizePolicy().hasHeightForWidth())
        self.brushButton.setSizePolicy(sizePolicy)
        self.brushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.brushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.brushButton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("images/paint-brush.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brushButton.setIcon(icon14)
        self.brushButton.setCheckable(True)
        self.brushButton.setObjectName("brushButton")
        self.gridLayout_2.addWidget(self.brushButton, 1, 7, 1, 1)
        self.colorButton_4 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_4.sizePolicy().hasHeightForWidth())
        self.colorButton_4.setSizePolicy(sizePolicy)
        self.colorButton_4.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_4.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_4.setText("")
        self.colorButton_4.setObjectName("colorButton_4")
        self.gridLayout_2.addWidget(self.colorButton_4, 0, 3, 1, 1)
        self.colorButton_5 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_5.sizePolicy().hasHeightForWidth())
        self.colorButton_5.setSizePolicy(sizePolicy)
        self.colorButton_5.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_5.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_5.setText("")
        self.colorButton_5.setObjectName("colorButton_5")
        self.gridLayout_2.addWidget(self.colorButton_5, 0, 4, 1, 1)
        self.rectButton = QtWidgets.QPushButton(self.widget_2)
        self.rectButton.setMinimumSize(QtCore.QSize(30, 30))
        self.rectButton.setMaximumSize(QtCore.QSize(30, 30))
        self.rectButton.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("images/layer-shape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rectButton.setIcon(icon15)
        self.rectButton.setCheckable(True)
        self.rectButton.setObjectName("rectButton")
        self.gridLayout_2.addWidget(self.rectButton, 0, 12, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.stampnextButton = QtWidgets.QPushButton(self.centralWidget)
        self.stampnextButton.setMinimumSize(QtCore.QSize(78, 55))
        self.stampnextButton.setMaximumSize(QtCore.QSize(78, 55))
        self.stampnextButton.setText("")
        self.stampnextButton.setIconSize(QtCore.QSize(80, 50))
        self.stampnextButton.setObjectName("stampnextButton")
        self.horizontalLayout_2.addWidget(self.stampnextButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 837, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFIle = QtWidgets.QMenu(self.menuBar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.fileToolbar = QtWidgets.QToolBar(MainWindow)
        self.fileToolbar.setIconSize(QtCore.QSize(16, 16))
        self.fileToolbar.setObjectName("fileToolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.fileToolbar)
        self.drawingToolbar = QtWidgets.QToolBar(MainWindow)
        self.drawingToolbar.setIconSize(QtCore.QSize(16, 16))
        self.drawingToolbar.setObjectName("drawingToolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.drawingToolbar)
        self.fontToolbar = QtWidgets.QToolBar(MainWindow)
        self.fontToolbar.setIconSize(QtCore.QSize(16, 16))
        self.fontToolbar.setObjectName("fontToolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.fontToolbar)
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setVisible(True)
        self.actionCopy.setObjectName("actionCopy")
        self.actionClearImage = QtWidgets.QAction(MainWindow)
        self.actionClearImage.setObjectName("actionClearImage")
        self.actionOpenImage = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("images/blue-folder-open-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenImage.setIcon(icon16)
        self.actionOpenImage.setObjectName("actionOpenImage")
        self.actionSaveImage = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("images/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveImage.setIcon(icon17)
        self.actionSaveImage.setObjectName("actionSaveImage")
        self.actionNewImage = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("images/document-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewImage.setIcon(icon18)
        self.actionNewImage.setObjectName("actionNewImage")
        self.actionBold = QtWidgets.QAction(MainWindow)
        self.actionBold.setCheckable(True)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("images/edit-bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBold.setIcon(icon19)
        self.actionBold.setObjectName("actionBold")
        self.actionItalic = QtWidgets.QAction(MainWindow)
        self.actionItalic.setCheckable(True)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("images/edit-italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionItalic.setIcon(icon20)
        self.actionItalic.setObjectName("actionItalic")
        self.actionUnderline = QtWidgets.QAction(MainWindow)
        self.actionUnderline.setCheckable(True)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("images/edit-underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUnderline.setIcon(icon21)
        self.actionUnderline.setObjectName("actionUnderline")
        self.actionFillShapes = QtWidgets.QAction(MainWindow)
        self.actionFillShapes.setCheckable(True)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("images/paint-can-color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFillShapes.setIcon(icon22)
        self.actionFillShapes.setObjectName("actionFillShapes")
        self.actionFlipHorizontal = QtWidgets.QAction(MainWindow)
        self.actionFlipHorizontal.setObjectName("actionFlipHorizontal")
        self.actionFlipVertical = QtWidgets.QAction(MainWindow)
        self.actionFlipVertical.setObjectName("actionFlipVertical")
        self.actionInvertColors = QtWidgets.QAction(MainWindow)
        self.actionInvertColors.setObjectName("actionInvertColors")
        self.actionClassifier = QtWidgets.QAction(MainWindow)
        self.actionClassifier.setObjectName("actionClassifier")
        self.menuFIle.addAction(self.actionNewImage)
        self.menuFIle.addAction(self.actionOpenImage)
        self.menuFIle.addAction(self.actionSaveImage)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionClearImage)
        self.menuEdit.addAction(self.actionFlipHorizontal)
        self.menuEdit.addAction(self.actionFlipVertical)
        self.menuEdit.addAction(self.actionInvertColors)
        self.menuEdit.addAction(self.actionClassifier)
        self.menuBar.addAction(self.menuFIle.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.fileToolbar.addAction(self.actionNewImage)
        self.fileToolbar.addAction(self.actionOpenImage)
        self.fileToolbar.addAction(self.actionSaveImage)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AI CANVAS"))
        self.menuFIle.setTitle(_translate("MainWindow", "FIle"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.fileToolbar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.drawingToolbar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.fontToolbar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionClearImage.setText(_translate("MainWindow", "Clear Image"))
        self.actionOpenImage.setText(_translate("MainWindow", "Open Image..."))
        self.actionSaveImage.setText(_translate("MainWindow", "Save Image As..."))
        self.actionNewImage.setText(_translate("MainWindow", "New Image"))
        self.actionBold.setText(_translate("MainWindow", "Bold"))
        self.actionBold.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionItalic.setText(_translate("MainWindow", "Italic"))
        self.actionItalic.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionUnderline.setText(_translate("MainWindow", "Underline"))
        self.actionFillShapes.setText(_translate("MainWindow", "Fill Shapes?"))
        self.actionFlipHorizontal.setText(_translate("MainWindow", "FlipHorizontal"))
        self.actionFlipVertical.setText(_translate("MainWindow", "FlipVertical"))
        self.actionInvertColors.setText(_translate("MainWindow", "Invert Colors"))
        self.actionClassifier.setText(_translate("MainWindow", "Number Classifier"))
